# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5435/organization_service_db
spring.datasource.username=saas_user
spring.datasource.password=pwd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
